### ISSUE TITLE
Error plotting on exFAT filesystem

### ISSUE THREAD

**Issue by rattle99** [Blagodarenko/XPlotter#1]
Just bought a 4TB WD Mybook External HDD. It's factory formatted the exFAT file system.
I tried to run Xplotter from the AIO wallet on it and got an error msg like this :

**"error creating stream for the file <directory> "**

Did anyone else face this? Is it a problem unique to the Mybook?

**Comment by BobbyT** [comment]
Try XPlotter v0.7, afaik v1.0 only works with NTFS, because only NTFS supports stream files.
https://msdn.microsoft.com/de-de/library/windows/desktop/ee681827(v=vs.85).aspx
