### ISSUE TITLE
printf not handling std::string correctly always

### ISSUE THREAD

**Issue by tarterp** [Blagodarenko/XPlotter#10]
Pull Request submitted to fix issue

colored message is printing garbled at times.

1>XPlotter.cpp(18): warning C4477: 'printf' : format string '%s' requires an argument of type 'char *', but variadic argument 1 has type 'std::string'
1>XPlotter.cpp(24): warning C4477: 'printf' : format string '%s' requires an argument of type 'char *', but variadic argument 1 has type 'std::string'

**Comment by Blagodarenko** [comment]
thank you!
