### ISSUE TITLE
linux?

### ISSUE THREAD

**Issue by vitaliy-kuzmich** [Blagodarenko/XPlotter#17]
Hello, I've found a lot of different soft for this coin, but did not found any up to date for linux. Please help me, I need wallet, plotter, miner for linux, and normal docs how to use it. As I understand this plotter only for windows ? Thanks a lot.

**Comment by Beddhist** [comment]
Hi Vitaliy,

For plotter I use cg_obup, creepMiner to mine and for wallet online at https://wallet.burstcoin.ro

Regards,
Peter.

**Comment by vitaliy-kuzmich** [comment]
thanks a lot.
