### ISSUE TITLE
Continue plotting. Possible or not?

### ISSUE THREAD

**Issue by yivo** [Blagodarenko/XPlotter#2]
Hey there!

First of all I want to thank you for developing and supporting this project.

v1.0 in release notes says:
`You can turn off Xplotter at any time, and later may continue plotting (works only at NTFS)`

But for me it doesn't work. It says that file exists and I should remove it first.

Am I doing anything wrong?

Thanks.

**Comment by ghost** [comment]
You need to match the filename of the plot you are trying to resume with the config.

eg.
```
17559140197979902351_20001_20000_20000
```
```
XPlotter_avx.exe -id 17559140197979902351 -sn 20001 -n 20000 -t 6 -path F:\burst\plots -mem 5G
```
