### ISSUE TITLE
Wrong filename

### ISSUE THREAD

**Issue by ludovicscribe** [Blagodarenko/XPlotter#29]
Hi,

The plot filename shoud be : `{Account ID}_{Start nonce}_{Nonces count}_{Stagger size}`

But with XPlotter, it is :  `{Account ID}_{Start nonce}_{Nonces count}_{Nonces count}`

I think there is a problem.

Have a good day !

**Comment by Creepsky** [comment]
Thats not a problem :D
When `{Stagger size}` == `{Nonces count}`, the plot file is optimized.
XPlotter is just optimizing your file.
