### ISSUE TITLE
Derivative works relicensed

### ISSUE THREAD

**Issue by atward** [Blagodarenko/XPlotter#5]
I would just like to bring [this](https://github.com/SamuelNZ/SPlotter) to your attention. It appears they have tried to present your work as their own under the MIT licence. This is in direct violation of the GPL.

**Comment by ghost** [comment]
Yeah. That isn't what happened at all and they already know I made SPlotter as it has been discussed in a forum that is not Github.

The license has been updated, Cheers for that. 

Also added a link to XPlotter to the README.
